### ISSUE TITLE
Activate language

### ISSUE THREAD

**Issue by rapdv** [helpdesk-z/translations#14]
How do I activate a language after I've placed the translated files in the right place?, I can't find any settings for changing the language..

**Comment by Mixerboy24** [comment]
Hi,

Change hdz/app/Config/Helpdesk.php from line 41 `const DEFAULT_LANG = 'en';` -> to your preferred language.

Example: 
```php
#Default helpdesk language
const DEFAULT_LANG = 'fi';
```

Atte / Mixer
